# Generated by Django 2.0.6 on 2018-10-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videogame_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
    ]
